### PR TITLE
Fix MaximumInscribedCircle::computeMaximumIterations for small values

### LINKED ISSUE #1129: MSVC 32-bit test failure with LargestEmptyCircle
With master and 3.12.2 the ctest suite has one failure with MSVC x86 (32-bit). Here is the relevant excerpt:
```
...
   24/466 Test  #24: unit-algorithm-construct-LargestEmptyCircle ................***Failed    0.10 sec
  ===============================
    GEOS Unit Test Suite
  ===============================
  
  geos::algorithm::construct::LargestEmptyCircle: ...............[21=F]
  
  ---> group: geos::algorithm::construct::LargestEmptyCircle, test: test<21>
       problem: assertion failed
       failed assertion: `x coordinate does not match: expected `-7.1150000000000006e+01` actual `-1.1111111100000000e+01` with precision `2.0000000000000000e+00``
  
  tests summary: failures:1 ok:15
...
```
This test is no issue for the x64 MSCV compiler, so it could be a possible 32-bit issue.

See test [here](https://github.com/libgeos/geos/blob/6201229a66ae3eef2b0c62cc39dbab48b2e3df7e/tests/unit/algorithm/construct/LargestEmptyCircleTest.cpp#L333-L343), with xref to https://trac.osgeo.org/postgis/ticket/5626 and #1003

### PR DESCRIPTION
**Pull request by mwtoews**
This fixes an issue with `MaximumInscribedCircle::computeMaximumIterations` that sometimes returns bogus values.

For example, with [this example](https://github.com/libgeos/geos/blob/6201229a66ae3eef2b0c62cc39dbab48b2e3df7e/tests/unit/algorithm/construct/LargestEmptyCircleTest.cpp#L333-L343) the number of iterations is needed by [`LargestEmptyCircle::compute()`](https://github.com/libgeos/geos/blob/4907d593aa6aa31c25dbe73933bf66995a04e498/src/algorithm/construct/LargestEmptyCircle.cpp#L235). The geometry calculates ncells=0.0903549, which would normally have a log value -2.40401. But the early cast to `size_t` doesn't correctly handle negative values meaning the maxIter is either 0 or 4294965296 (i.e. it's up to the compiler to decide). This fix will re-establish the maxIter to 4000 for small "ncells" values (less than 1). The bug with MSVC 32-bit is that it was zero, meaning no iteration.

<s>Also clean-up one MSVC warning.</s>

Closes #1129

### CODE REVIEW

**Comment by mwtoews** [comment]
Potentially a similar fix would be good with JTS [here](https://github.com/locationtech/jts/blob/0d5eac992da509d052e3d23b522c375ba902cd86/modules/core/src/main/java/org/locationtech/jts/algorithm/construct/MaximumInscribedCircle.java#L109) too.

**Comment by dr-jts** [comment]
Might be nice to keep the codebases more in synch - by using the signed int idea?

File: tests/unit/coverage/CoverageSimplifierTest.cpp [hunk 1]
```diff
@@ -476,6 +477,7 @@ void object::test<30> ()
         CoverageSimplifier::simplify(input, 10);
     }
     catch (geos::util::IllegalArgumentException& iae) {
+        ::geos::ignore_unused_variable_warning(iae);
```
Comment (dbaston) [inline tests/unit/coverage/CoverageSimplifierTest.cpp:480]:
```suggestion
    catch (geos::util::IllegalArgumentException&) {
```

File: tests/unit/coverage/CoverageSimplifierTest.cpp [hunk 2]
```diff
@@ -475,7 +475,7 @@ void object::test<30> ()
         std::vector<std::unique_ptr<Geometry>> result =
         CoverageSimplifier::simplify(input, 10);
     }
-    catch (geos::util::IllegalArgumentException& iae) {
+    catch (geos::util::IllegalArgumentException&) {
```
Comment (dr-jts) [inline tests/unit/coverage/CoverageSimplifierTest.cpp:478]: Any reason this change is in this PR?

Comment (mwtoews) [reply tests/unit/coverage/CoverageSimplifierTest.cpp]: It's only mildly related to MSVC where the primary fix is for, but it is otherwise unrelated. I'm fine to remove it.

Comment (dr-jts) [reply tests/unit/coverage/CoverageSimplifierTest.cpp]: Probably best to put in a separate PR, to avoid any confusion down the road.

**Comment by mwtoews** [comment]
Cherry-picked to the `3.12` maintenance branch 8fa289cf0146780a0be01e97501589b5a29224c4
Is this NEWS-worthy for 3.12.3? It seems so trivial and specific to me to not.

**Comment by dr-jts** [comment]
>  Is this NEWS-worthy for 3.12.3? It seems so trivial and specific to me to not.

Agreed, probably no need to add to NEWS.
