### PR TITLE
Fix overlay heuristic for GeometryCollections with empty elements

### LINKED ISSUE #1224: Union Operations returns collections containing empty elements
Relates to: https://trac.osgeo.org/postgis/ticket/5835

Reproduce in GEOS:
```
geosop -a 'GEOMETRYCOLLECTION(POLYGON EMPTY, POINT EMPTY, LINESTRING(10 10, 10 10))' -b 'POINT(1 1)' union
-- reuslt:{GEOMETRYCOLLECTION (POLYGON EMPTY, POINT EMPTY, LINESTRING (10 10, 10 10), POINT (1 1))}

geosop -a 'GEOMETRYCOLLECTION(POLYGON EMPTY, POINT EMPTY, LINESTRING(10 10, 10 10), POINT(1 1))' unaryUnion
-- result:{GEOMETRYCOLLECTION (POINT (1 1), LINESTRING EMPTY)}
```

### PR DESCRIPTION
**Pull request by dr-jts**
This fixes the behaviour of the "combine disjoint" overlay heuristic for GeometryCollections containing empty elements (which are now removed).   

Fixes #1224 

(Note: part of #1224 requires #1136 to be fixed as well).

The PR also:
* centralizes overlay heuristic logic in `HeuristicOverlay` (moving code from `Geometry`)
* modularizes the `HeuristicOverlay` code
* improves `HeuristicOverlay` semantics to return empty results as an empty typed atomic geometry instead of an empty GeometryCollection (this matches `OverlayNG`)
* removes unnecessary dependencies on `HeuristicOverlay` (by calling `OverlayNGRobust` directly where it is known the heuristics do not apply)
* fixes `XMLTester` to correctly handle operation A & B argument switching

### CODE REVIEW

File: src/geom/HeuristicOverlay.cpp [hunk 1]
```diff
@@ -40,31 +47,63 @@ namespace geom { // geos::geom
...
 
+bool isDisjointNonEmpty(const Geometry* g0, const Geometry* g1)
+{
+    if (g0->isEmpty() && g1->isEmpty())
+        return false;
+    return ! g0->getEnvelopeInternal()->intersects(g1->getEnvelopeInternal());
+}
+
+void 
+extractELements(const Geometry* g, std::vector<std::unique_ptr<Geometry>>& v)
```
Comment (dbaston) [inline src/geom/HeuristicOverlay.cpp:58]:
```suggestion
extractElements(const Geometry* g, std::vector<std::unique_ptr<Geometry>>& v)
```

File: src/geom/HeuristicOverlay.cpp [hunk 2]
```diff
@@ -40,31 +47,63 @@ namespace geom { // geos::geom
...
+{
+    const GeometryCollection* coll;
+    if (nullptr != (coll = dynamic_cast<const GeometryCollection*>(g))) {
```
Comment (dbaston) [inline src/geom/HeuristicOverlay.cpp:61]:
```suggestion
    if (const auto* coll = dynamic_cast<const GeometryCollection*>(g))) {
```

File: src/geom/HeuristicOverlay.cpp [hunk 3]
```diff
@@ -108,6 +148,24 @@ HeuristicOverlay(const Geometry* g0, const Geometry* g1, int opCode)
...
+    StructuredCollection s1(g1);
+    switch (opCode) {
+    case OverlayNG::UNION:
+        return s0.doUnion(s1);
+    case OverlayNG::DIFFERENCE:
+        return s0.doDifference(s1);
+    case OverlayNG::SYMDIFFERENCE:
+        return s0.doSymDifference(s1);
+    default: // only OverlayNG::INTERSECTION
+        return s0.doIntersection(s1);
```
Comment (dbaston) [inline src/geom/HeuristicOverlay.cpp:165]:
```suggestion
    case OverlayNG::INTERSECTION:
        return s0.doIntersection(s1);    
    default:
        throw util::IllegalArgumentException("Invalid opcode");
```

File: tests/xmltester/XMLTester.cpp [hunk 4]
```diff
@@ -178,6 +178,17 @@ tolower(std::string& str)
         );
 }
 
+void
+toupper(std::string& str)
```
Comment (dbaston) [inline tests/xmltester/XMLTester.cpp:182]: Already implemented in `geos/util/string.h`

Comment (dr-jts) [reply tests/xmltester/XMLTester.cpp:182]: great, thanks

File: src/geom/HeuristicOverlay.cpp (hunk 1 above)
Comment (dr-jts) [reply src/geom/HeuristicOverlay.cpp:58]: what is the change?

Comment (dbaston) [reply src/geom/HeuristicOverlay.cpp:58]: second letter of "elements"
