### PR TITLE
Backport GH-953 to 3.11 branch

### LINKED ISSUE #1034: Possible backport for concaveHull
As reported https://github.com/shapely/shapely/issues/1971 there is an issue with this example:
```bash
$ ./geos-3.12.0/bin/geosop -a "MULTIPOINT ((175682.210293 505233.365178), (175682.210295 505233.365177), (175684.375108 505254.524644), (175684.375109 505254.524642), (175683.226468 505243.284373))" concaveHull 0.0
Segmentation fault (core dumped)
```
this was recently resolved for GEOS 3.12.1 with this expected result:
```bash
$ ./geos-3.12.1/bin/geosop -a "MULTIPOINT ((175682.210293 505233.365178), (175682.210295 505233.365177), (175684.375108 505254.524644), (175684.375109 505254.524642), (175683.226468 505243.284373))" concaveHull 0.0
POLYGON ((175682.210293 505233.365178, 175684.375108 505254.524644, 175684.375109 505254.524642, 175683.226468 505243.284373, 175682.210295 505233.365177, 175682.210293 505233.365178))
```
The mystery is how this was resolved, as there is nothing obvious in NEWS.md to backport this fix for older branches (e.g. a forthcoming 3.11.4). Does this look familiar to anyone?

### PR DESCRIPTION
**Pull request by mwtoews**
Backport of #953 to 3.11 branch

Closes #1034

### CODE REVIEW

File: tests/unit/algorithm/hull/ConcaveHullTest.cpp [hunk 1]
```diff
@@ -243,6 +243,28 @@ void object::test<15>()
...
 
+//------------------------------------------------
+
+// These tests test that the computed Delaunay triangulation is correct
+// See https://github.com/locationtech/jts/pull/1004
+  
+// testRobust_GEOS946
+template<>
+template<>
+void object::test<20>()
```
Comment (mwtoews) [inline tests/unit/algorithm/hull/ConcaveHullTest.cpp:254]: should these numbers be reset to 16? Or leave as-is in-case there are other backports from main (which has the missing 16-19 tests). It doesn't seem to mind that there are gaps of test numbers.

Comment (mwtoews) [reply tests/unit/algorithm/hull/ConcaveHullTest.cpp:254]: I've decided to leave these alone. Previously I would have reset them, but it makes potential other backports difficult to place in if they have tests before/after these.
